<?php

namespace Moosh2\Service;

class PhpMusselSignatureManager
{
    private string $signatureDir;

    /**
     * URL => target filename. Files are stored in phpMussel's native format
     * with the "phpMussel" header intact — the Loader requires it.
     *
     * Only phpMussel-format signatures are downloaded. ClamAV-format files
     * (like clamav.hdb) are deliberately excluded: phpMussel's loader skips
     * any file whose first 9 bytes aren't the literal string "phpMussel",
     * so they'd be dead weight here.
     *
     * @var array<string, string>
     */
    private const SOURCES = [
        'https://raw.githubusercontent.com/phpMussel/Signatures/master/misc/phpmussel.hdb.gz' => 'phpmussel.hdb',
        'https://raw.githubusercontent.com/phpMussel/Signatures/master/misc/phpmussel.ndb.gz' => 'phpmussel.ndb',
        'https://raw.githubusercontent.com/phpMussel/Signatures/master/misc/phpmussel.db.gz'  => 'phpmussel.db',
        'https://raw.githubusercontent.com/phpMussel/Signatures/master/misc/phpmussel.fdb.gz' => 'phpmussel.fdb',
    ];

    public function __construct(?string $signatureDir = null)
    {
        $this->signatureDir = $signatureDir
            ?? (getenv('HOME') ?: sys_get_temp_dir()) . '/.moosh2/phpmussel-signatures';
    }

    public function getSignatureDir(): string
    {
        return $this->signatureDir;
    }

    public function getConfigPath(): string
    {
        return $this->signatureDir . '/phpmussel.ini';
    }

    public function getCacheDir(): string
    {
        return dirname($this->signatureDir) . '/phpmussel-cache';
    }

    public function getQuarantineDir(): string
    {
        return dirname($this->signatureDir) . '/phpmussel-quarantine';
    }

    public function ensureDirectory(): void
    {
        if (!is_dir($this->signatureDir)) {
            mkdir($this->signatureDir, 0755, true);
        }
    }

    /**
     * Download and decompress every signature file, then write the
     * phpMussel config that activates them.
     *
     * @return array<string, string> filename => status message
     */
    public function update(): array
    {
        $this->ensureDirectory();
        $results = [];

        foreach (self::SOURCES as $url => $filename) {
            $target = $this->signatureDir . '/' . $filename;

            $raw = @file_get_contents($url, false, stream_context_create([
                'http' => [
                    'timeout'         => 60,
                    'user_agent'      => 'moosh2-phpmussel-updater/1.0',
                    'follow_location' => 1,
                ],
            ]));

            if ($raw === false || $raw === '') {
                $results[$filename] = "FAILED (could not download from $url)";
                continue;
            }

            if (str_ends_with($url, '.gz')) {
                $decoded = @gzdecode($raw);
                if ($decoded === false || $decoded === '') {
                    $results[$filename] = "FAILED (could not gunzip $url)";
                    continue;
                }
                $raw = $decoded;
            }

            // phpMussel signature files MUST retain the "phpMussel" header;
            // stripping it would make them unreadable by the Loader.
            if (!str_starts_with($raw, 'phpMussel')) {
                $results[$filename] = "FAILED (missing phpMussel header in $url)";
                continue;
            }

            file_put_contents($target, $raw);
            $results[$filename] = sprintf('OK (%d bytes)', strlen($raw));
        }

        // Write the config that activates every downloaded file and
        // narrows the extension blacklist.
        //
        // Why the blacklist override: phpMussel's default
        // files.filetype_blacklist (in assets/config.yml) includes "php*"
        // because phpMussel is designed as an upload scanner, where .php
        // is dangerous. A Moodle plugin is entirely .php files by design,
        // so the default would flag every file in the tree as a hit. We
        // keep the value non-empty because an empty string is treated as
        // "not set" by phpMussel's fallback() and would reapply the
        // default; instead we list only extensions that are never
        // legitimate in a Moodle plugin source tree. Signature matching,
        // chameleon detection, and archive inspection are all still
        // active — only the extension blanket-block is narrowed.
        $active = [];
        foreach (self::SOURCES as $filename) {
            if (is_file($this->signatureDir . '/' . $filename)) {
                $active[] = $filename;
            }
        }

        $ini = "; Generated by moosh2 plugin:phpmuslescan:update-signatures\n"
             . "; Do not edit by hand — re-run that command to regenerate.\n"
             . "\n"
             . "[signatures]\n"
             . 'active = "' . implode(',', $active) . "\"\n"
             . "\n"
             . "[files]\n"
             . "; Narrowed from the phpMussel default (which includes php*).\n"
             . "; Only extensions that are never legitimate in a Moodle plugin\n"
             . "; source tree. Signature matching and chameleon detection are\n"
             . "; unaffected.\n"
             . 'filetype_blacklist = "exe,dll,scr,com,bat,cmd,ps1,vbs,vbe,wsf,hta,lnk,pif,msi,msp"'
             . "\n";

        file_put_contents($this->getConfigPath(), $ini);

        return $results;
    }
}