name: Build and Test

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  MOODLE_DIR: "/github/workspace/moodle"
  MOODLE_REPOSITORY: "moodle/moodle"
  PHP_ENV: mysqli, pdo_mysql, gd, intl, mbstring, xml, zip, curl

jobs:

  build:
    runs-on: ubuntu-latest
    container: composer:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Trust the checked-out workspace
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Set composer package name to this repository
        run: |
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          sed -i "s#\"name\": \"tmuras/moosh\"#\"name\": \"${REPO_NAME}\"#" composer.json
      - name: Build code
        run: composer install
      - name: Zip build
        run: zip -r vendor.zip vendor
      - name: Upload build
        uses: actions/upload-artifact@v7
        with:
          name: moosh-vendor
          path: vendor.zip
            
  test:
    strategy:
      fail-fast: false
      matrix:
        image: ["8.3", "8.4", "8.5"]
        moodle_branch: ["MOODLE_502_STABLE"]
    runs-on: ubuntu-latest
    container: php:${{ matrix.image }}-cli-alpine
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: moodle_password
          MYSQL_DATABASE: moodledb
          MYSQL_USER: moodleuser
          MYSQL_PASSWORD: moodle_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Remove vendor folder
        run:  rm -rf vendor
      - name: Download build
        uses: actions/download-artifact@v8
        with:
          name: moosh-vendor
      - name: Unzip build
        run: unzip vendor.zip
      - name: Run preliminary test
        id: prelim_test
        run: php moosh.php -V | grep -E "moosh 2\."
      - name: Run diagnostic
        if: failure() && steps.prelim_test.outcome == 'failure'
        run: php moosh.php
      - name: Lint files
        run: |
          ls    
          find . -name '*.php' -not -path '*/tests/*' -print0 | xargs -0 -n1 php -l
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          extensions: ${{ env.PHP_ENV }}
      - name: Checkout Moodle Repository
        uses: actions/checkout@v7
        with:
          repository: ${{ env.MOODLE_REPO }}
          path: ${{ env.MOODLE_DIR }}
          ref: ${{ matrix.moodle_branch }}
          fetch-depth: 1
      - name: Install Moodle Instance
        run: |
          mkdir -p $HOME/moodledata
          chmod 777 $HOME/moodledata

          php $MOODLE_DIR/admin/cli/install.php \
            --non-interactive \
            --lang=en \
            --wwwroot="http://localhost:8000" \
            --dataroot="$HOME/moodledata" \
            --dbtype=mysqli \
            --dbhost=127.0.0.1 \
            --dbname=moodledb \
            --dbuser=moodleuser \
            --dbpass=moodle_password \
            --fullname="Moosh Test Moodle" \
            --shortname="moodle_test" \
            --adminuser=admin \
            --adminpass=Admin123! \
            --agree-license
      - name: Populating test data
        run: |
            php "tests/test_data_setup_moodle52/setup_testdata.php" $MOODLE_DIR
