name: Build and Test

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    container: composer:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Trust the checked-out workspace
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Set composer package name to this repository
        run: |
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          sed -i "s#\"name\": \"tmuras/moosh\"#\"name\": \"${REPO_NAME}\"#" composer.json
      - name: Build code
        run: composer install
      - name: Zip build
        run: zip -r vendor.zip vendor
      - name: Upload build
        uses: actions/upload-artifact@v7
        with:
          name: moosh-vendor
          path: vendor.zip
            
  test:
    strategy:
      fail-fast: false
      matrix:
        image: ["8.3", "8.4", "8.5"]
    runs-on: ubuntu-latest
    container: php:${{ matrix.image }}-cli-alpine
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Remove vendor folder
        run:  rm -rf vendor
      - name: Download build
        uses: actions/download-artifact@v8
        with:
          name: moosh-vendor
      - name: Unzip build
        run: unzip vendor.zip
      - name: Run preliminary test
        id: prelim_test
        run: php moosh.php -V | grep -E "moosh 2\."
      - name: Run diagnostic
        if: failure() && steps.prelim_test.outcome == 'failure'
        run: php moosh.php
      - name: Lint files
        run: |
          ls    
          rm includes/config*class.php
          rm -rf vendor external
          find . -name '*.php' -not -path '*/tests/*' -print0 | xargs -0 -n1 php -l        
      - name: Setup Moodle for Testing
        run: test/test_data_setup_moodle52/fully_reinstall.sh

